# Generated by Django 3.2.23 on 2025-02-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
