# Generated by Django 5.1.6 on 2025-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('admin', 'Admin'), ('paloma gatabaki', 'Paloma Gatabaki')], default='Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('press release', 'Press Release'), ('opinion', 'Opinion'), ('notice', 'Notice')], default='Press Release', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
