# Generated by Django 5.1.6 on 2025-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0005_post_author_post_category_post_custom_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('paloma gatabaki', 'Paloma Gatabaki')], max_length=50),
        ),
    ]
