# Generated by Django 5.1.6 on 2025-03-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0008_author_created_at_author_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
