# Generated by Django 5.1.6 on 2025-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0012_category_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
