# Generated by Django 5.1.6 on 2025-03-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiper', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='custom_author',
        ),
    ]
